version: '3.8'

services:
  pikol:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./servers:/app/servers
    environment:
      - TOKEN=${TOKEN}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  ollama_data: